New&edit allergen popup
cristinadumitrescu98/hibyte-project pull request #3
Opened 2023-01-31 16:14 UTC by cristinadumitrescu98

2023-02-03 08:23 UTC, daianaiurescu commented on src/app/components/allergen-table/allergen-table.component.css
> +/* :host::ng-deep.edit-popup {
commented code

2023-02-03 08:27 UTC, daianaiurescu commented on src/app/components/allergen-table/allergen-table.component.ts
>      this.allergenService.fetchAllergens().subscribe((allergens) => {
you can write this in only one line. you only need the {} inside subscribe/filter/forEach etc. if you return the value or have multiple method calls

2023-02-03 08:29 UTC, daianaiurescu commented on src/app/components/allergen-table/allergen-table.component.ts
> +    this.selectedAllergen.name = allergen.name;
since you are assigning the allergen value to this.selectedAllergen, you don't need to separately assign its values, so this.selectedAllergen.name = allergen.name is not needed because this.selectedAllergen = allergen already does it

2023-02-03 08:32 UTC, daianaiurescu commented on src/app/components/allergen-table/allergen-table.component.ts
> +          this.allergens.filter((allergen) => {
this.allergens.filter((allergen) => allergen.id != this.currentDeleteId) does the same thing as ... {return allergen.id != this.currentDeleteId). Usually, you can write filter expressions in one line and only use the return if there is some extra logic being done before returning the value

2023-02-03 08:35 UTC, daianaiurescu commented on src/app/components/header/header.component.css
>    height: 86.732;
i don't think this does anything, because usually you need to specify the unit (%, px, rem, vh, etc.), but please check if this style is applied. Also, since the image sizes inside the media query is set in rem, please change it here also in rem (rem is always better for responsiveness than px)

2023-02-03 08:37 UTC, daianaiurescu commented on src/app/components/ingredient-table/ingredient-table.component.ts
> +    this.displayEditPopup = true;
if you are using all these variables just to get/set the values inside the popup form, you can get rid of all of them and work directly with ingredient.<property>

2023-02-03 08:37 UTC, daianaiurescu commented on src/app/components/ingredient-table/ingredient-table.component.ts
> +          this.ingredients.filter((ingredient) => {
same thing here with the filtering expression and the unecesssary {}

2023-02-03 09:27 UTC, DrBaxR requested changes

2023-02-03 09:27 UTC, DrBaxR commented on src/app/components/allergen-table/allergen-table.component.css
> +    padding-top: 10px;
I see that you are using `rem`s in some places. When using responsive units, you should use them everywhere since otherwise you will reach a point where you'll realize that not all parts of your application are responsive. Please switch the `px` to `rem` in the places where you used `px`.

The only exception to the rule may be cases when you only need small measures values that won't change on smaller/larger devices. For example, this is fine:

```css
border: 1px solid var(--light-sea-teal);
```

2023-02-03 09:27 UTC, DrBaxR commented on src/app/components/ingredient-table/ingredient-table.component.ts
> +    this.displayEditPopup = true;
I'd also like to add something: When working with larger/more complex forms it's generally a better to use [reactive forms](https://angular.io/guide/reactive-forms), since they have a nicer interface and are more scalable than template driven forms (the ones where you use `ngModel` in the HTML file).

There is not need to switch to reactive forms in this component, just a suggestion for the future.

2023-02-03 09:27 UTC, DrBaxR commented on src/app/services/allergen.service.ts
> +  updateAllergen(allergen: Allergen): Observable<Allergen> {
The services `AllergenService` and `IngredientService` are very similar. Please try to make a new service `DataService`, or something like that can replace both of these services (and maybe other services that do a similar thing).

My suggestion for this refactoring is to create a new interface/class (depending on what you used to represent your data model):

```ts
interface DataItem {
    id: number;
}
```

Make `Allergen` and `Ingredient` implement/extend the interface/class you just created:

```ts
interface Allergen implements DataItem { \* ... *\ }

interface Ingredient implements DataItem { \* ... *\ }
```

And then finally create the new service that looks something like this:

```ts
export enum ItemKey {
    ALLERGEN = 'allergens',
    INGREDIENT = 'ingredient',
    // ...
}

export class DataService {
    fetch(itemKey: ItemKey) { /* ... */ }
    add(itemKey: ItemKey, item: DataItem) { /* ... */ }
    update(item: DataItem) { /* ... */ }
    delete(id: number) { /* ... */ }
}
```

2023-02-06 11:56 UTC, cristinadumitrescu98 commented on src/app/components/allergen-table/allergen-table.component.css
> +/* :host::ng-deep.edit-popup {
✅

2023-02-06 11:58 UTC, cristinadumitrescu98 commented on src/app/components/allergen-table/allergen-table.component.ts
>      this.allergenService.fetchAllergens().subscribe((allergens) => {
✅

2023-02-06 11:59 UTC, cristinadumitrescu98 commented on src/app/components/allergen-table/allergen-table.component.ts
> +    this.selectedAllergen.name = allergen.name;
✅

2023-02-06 12:07 UTC, cristinadumitrescu98 commented on src/app/components/allergen-table/allergen-table.component.ts
> +          this.allergens.filter((allergen) => {
✅

2023-02-06 12:10 UTC, cristinadumitrescu98 commented on src/app/components/header/header.component.css
>    height: 86.732;
✅

2023-02-06 12:11 UTC, cristinadumitrescu98 commented on src/app/app.component.css
> +  border-bottom-left-radius: 5px;
✅

2023-02-06 12:21 UTC, cristinadumitrescu98 commented on src/app/components/add-edit-allergen-popup/add-edit-allergen-popup.component.ts
> +  @Output() closeAddEditPopup: EventEmitter<boolean> =
✅

2023-02-06 12:47 UTC, cristinadumitrescu98 commented on src/app/components/allergen-table/allergen-table.component.css
> +    padding-top: 10px;
✅

2023-02-06 12:52 UTC, cristinadumitrescu98 commented on src/app/components/ingredient-table/ingredient-table.component.ts
> +    this.displayEditPopup = true;
✅

2023-02-06 12:53 UTC, cristinadumitrescu98 commented on src/app/components/ingredient-table/ingredient-table.component.ts
> +          this.ingredients.filter((ingredient) => {
✅

2023-02-06 14:16 UTC, cristinadumitrescu98 commented on src/app/services/allergen.service.ts
> +  updateAllergen(allergen: Allergen): Observable<Allergen> {
✅ - tried my best :)))

2023-02-09 10:17 UTC, daianaiurescu approved these changes

2023-02-09 11:05 UTC, merged